name: Build and test

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-and-test:
    strategy:
      matrix:
        python-version: ['3.x', '3.8']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install .
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest -v -rs --doctest-modules --cov whatami --cov-report term-missing whatami
